version: '2'
services:
    testapplication-app:
        image: testapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://testapplication-mariadb:3306/testapplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    testapplication-mariadb:
        extends:
            file: mariadb.yml
            service: testapplication-mariadb
